server.port=8080

# Conexão Supabase via Session Pooler (Garante resolução em redes IPv4 / Wi-Fi local)
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require&user=postgres.furiuxqvixykdzxptsuf&prepareThreshold=0
spring.datasource.username=postgres.furiuxqvixykdzxptsuf
spring.datasource.password=XAx7RVA9ox0ah0rj
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Configurações de e-mail (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=wagneranderson499@gmail.com
spring.mail.password=jtcg kobu uiap mmyf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2 TLSv1.3