
server.port=8080


spring.datasource.url=jdbc:postgresql://db.furiuxqvixykdzxptsuf.supabase.co:6543/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=I5aMf02p6MfrSNAN
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=app

# envio de email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=wagneranderson499@gmail.com
spring.mail.password=jtcg kobu uiap mmyf

# email autenticação
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2 TLSv1.3